apiVersion: v1
kind: ConfigMap
metadata:
  name: proton-affiliate-webapp-config
data:
  # webapp
  PORT: '${PORT}'
  REACT_APP_TITLE: '${REACT_APP_TITLE}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proton-affiliate-postgres-config
data:
  # postgres
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  POSTGRES_DB: '${POSTGRES_DB}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proton-affiliate-hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
  HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
  HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
  HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
  HAPI_NETWORK_CREATOR_ACCOUNT: '${HAPI_NETWORK_CREATOR_ACCOUNT}'
  HAPI_NETWORK_CREATOR_PASSWORD: '${HAPI_NETWORK_CREATOR_PASSWORD}'
  HAPI_NETWORK_WALLET: '${HAPI_NETWORK_WALLET}'
  HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
  HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  HAPI_AFFILIATE_ACCOUNT: '${HAPI_AFFILIATE_ACCOUNT}'
  HAPI_AFFILIATE_PASSWORD: '${HAPI_AFFILIATE_PASSWORD}'
  HAPI_AFFILIATE_VERIFY_EXPIRED_INTERVAL: '${HAPI_AFFILIATE_VERIFY_EXPIRED_INTERVAL}'
  HAPI_AFFILIATE_CLEAR_REFERRALS_INTERVAL: '${HAPI_AFFILIATE_CLEAR_REFERRALS_INTERVAL}'
  HAPI_AFFILIATE_SET_RATE_INTERVAL: '${HAPI_AFFILIATE_SET_RATE_INTERVAL}'
  HAPI_DEMUX_START_AT_BLOCK: '${HAPI_DEMUX_START_AT_BLOCK}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proton-affiliate-hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
